import jsPDF from "jspdf";

export const generatePDF = ({ result, fileCount }) => {
  const doc = new jsPDF("p", "mm", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // 🔹 Watermark
  const addWatermark = () => {
    doc.setTextColor(200);
    doc.setFontSize(40);
    doc.text("MedDocAI", pageWidth / 2, pageHeight / 2, {
      align: "center",
      angle: 45,
    });
    doc.setTextColor(0);
  };

  addWatermark();

  // 🔹 Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("MedDocAI – Medical Document Analysis", 20, 30);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Documents analyzed: ${fileCount}`,
    20,
    40
  );

  // 🔹 Section: Overview
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Overview of Your Documents", 20, 55);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(result.summary, 20, 65, { maxWidth: 170 });

  let currentY = doc.lastAutoTable?.finalY || 90;

  // 🔹 Section: Insights
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Detailed Insights & Observations", 20, currentY + 15);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  let y = currentY + 25;
  result.details.forEach((point) => {
    if (y > pageHeight - 30) {
      doc.addPage();
      addWatermark();
      y = 30;
    }
    doc.text(`• ${point}`, 20, y, { maxWidth: 170 });
    y += 8;
  });

  // 🔹 Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by MedDocAI | Developed by Shashwat Singh",
    pageWidth / 2,
    pageHeight - 15,
    { align: "center" }
  );

  // 🔹 Disclaimer
  doc.setFontSize(9);
  doc.text(
    "This document is generated for informational purposes only and does not replace professional medical advice.",
    pageWidth / 2,
    pageHeight - 8,
    { align: "center", maxWidth: 180 }
  );

  doc.save("MedDocAI_Report.pdf");
};
